"""add initial models

Revision ID: 7615aa79d0ae
Revises: 564b90ad7175
Create Date: 2026-01-27 16:17:46.758875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7615aa79d0ae'
down_revision: Union[str, Sequence[str], None] = '564b90ad7175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_metadata',
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='使用した AI モデル名'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='推定信頼度（0.0〜1.0）'),
    sa.Column('source', sa.String(length=100), nullable=True, comment='推定元（interaction / manual など）'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='formegot'
    )
    op.create_table('calendar_events',
    sa.Column('external_id', sa.String(length=255), nullable=False, comment='外部カレンダーのイベントID'),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True, comment='google / apple など'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    schema='formegot'
    )
    op.create_table('communities',
    sa.Column('name', sa.String(length=100), nullable=False, comment='コミュニティ名'),
    sa.Column('description', sa.Text(), nullable=True, comment='概要・説明'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='親コミュニティ'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['formegot.communities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='formegot'
    )
    op.create_table('persons',
    sa.Column('name', sa.String(length=100), nullable=False, comment='表示名・呼称'),
    sa.Column('canonical_name', sa.String(length=100), nullable=True, comment='正規化名（重複防止・検索用）'),
    sa.Column('description', sa.Text(), nullable=True, comment='人物の概要・補足説明'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name'),
    schema='formegot'
    )
    op.create_table('reminders',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False, comment='通知予定時刻'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='formegot'
    )
    op.create_table('tags',
    sa.Column('name', sa.String(length=50), nullable=False, comment='タグ名（表示用）'),
    sa.Column('slug', sa.String(length=50), nullable=True, comment='正規化タグ名（検索・統合用）'),
    sa.Column('description', sa.Text(), nullable=True, comment='タグの説明・意味'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug'),
    schema='formegot'
    )
    op.create_table('topics',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='話題の有効期限'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='formegot'
    )
    op.create_table('community_trees',
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['formegot.communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['formegot.communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'child_id', name='uq_community_tree'),
    schema='formegot'
    )
    op.create_table('insights',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False, comment='インサイト種別'),
    sa.Column('content', sa.Text(), nullable=False, comment='気づきの内容'),
    sa.Column('confidence', sa.Integer(), nullable=True, comment='確信度（例: 1〜5）'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['formegot.persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='formegot'
    )
    op.create_table('interactions',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False, comment='接触タイプ'),
    sa.Column('content', sa.Text(), nullable=True, comment='会話内容・出来事'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['formegot.persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='formegot'
    )
    op.create_table('meeting_snapshots',
    sa.Column('calendar_event_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False, comment='直前確認用の要約'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['calendar_event_id'], ['formegot.calendar_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='formegot'
    )
    op.create_table('memberships',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True, comment='community role'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['formegot.communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['formegot.persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'community_id', name='uq_person_community'),
    schema='formegot'
    )
    op.create_table('person_profiles',
    sa.Column('person_id', sa.UUID(), nullable=False, comment='対応する Person'),
    sa.Column('first_impression', sa.String(length=200), nullable=True, comment='第一印象（短文）'),
    sa.Column('intuition', sa.Text(), nullable=True, comment='直感・感覚的なメモ'),
    sa.Column('vibe_score', sa.Integer(), nullable=True, comment='雰囲気スコア（例: -5〜+5）'),
    sa.Column('notes', sa.Text(), nullable=True, comment='その他の特徴・補足'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['formegot.persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id'),
    schema='formegot'
    )
    op.create_table('person_tags',
    sa.Column('person_id', sa.UUID(), nullable=False, comment='対象 Person'),
    sa.Column('tag_id', sa.UUID(), nullable=False, comment='付与された Tag'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['formegot.persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['formegot.tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'tag_id', name='uq_person_tag'),
    schema='formegot'
    )
    op.create_table('relations',
    sa.Column('from_person_id', sa.UUID(), nullable=False),
    sa.Column('to_person_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False, comment='関係タイプ'),
    sa.Column('strength', sa.Integer(), nullable=True, comment='関係強度（例: 1〜5）'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_person_id'], ['formegot.persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_person_id'], ['formegot.persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='formegot'
    )
    op.create_table('relationship_tasks',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['formegot.persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='formegot'
    )
    op.create_table('reminder_triggers',
    sa.Column('reminder_id', sa.UUID(), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False, comment='time / calendar など'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reminder_id'], ['formegot.reminders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='formegot'
    )
    op.create_table('interaction_tags',
    sa.Column('interaction_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['formegot.interactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['formegot.tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interaction_id', 'tag_id', name='uq_interaction_tag'),
    schema='formegot'
    )
    op.create_table('parsed_notes',
    sa.Column('source_id', sa.UUID(), nullable=False, comment='解析元（例: Interaction）'),
    sa.Column('content', sa.Text(), nullable=False, comment='AI による構造化結果（JSON / 要約文など）'),
    sa.Column('metadata_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['metadata_id'], ['formegot.ai_metadata.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['formegot.interactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='formegot'
    )
    op.create_table('task_histories',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['formegot.relationship_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='formegot'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_histories', schema='formegot')
    op.drop_table('parsed_notes', schema='formegot')
    op.drop_table('interaction_tags', schema='formegot')
    op.drop_table('reminder_triggers', schema='formegot')
    op.drop_table('relationship_tasks', schema='formegot')
    op.drop_table('relations', schema='formegot')
    op.drop_table('person_tags', schema='formegot')
    op.drop_table('person_profiles', schema='formegot')
    op.drop_table('memberships', schema='formegot')
    op.drop_table('meeting_snapshots', schema='formegot')
    op.drop_table('interactions', schema='formegot')
    op.drop_table('insights', schema='formegot')
    op.drop_table('community_trees', schema='formegot')
    op.drop_table('topics', schema='formegot')
    op.drop_table('tags', schema='formegot')
    op.drop_table('reminders', schema='formegot')
    op.drop_table('persons', schema='formegot')
    op.drop_table('communities', schema='formegot')
    op.drop_table('calendar_events', schema='formegot')
    op.drop_table('ai_metadata', schema='formegot')
    # ### end Alembic commands ###
